### ISSUE TITLE
程序运行环境

### ISSUE THREAD

**Issue by 30CodeMaker** [jsp666/CEMBR#1]
作者大大您好，我对您的工作非常感兴趣，想复现您的工作，可以给出您的程序运行环境吗谢谢！

**Comment by jsp666** [comment]
硬件环境：15-core  Intel Xeon CPU of 2.6GHz, NVIDIA GeForce RTX 3080,  and 80 GB of RAM
软件环境：Tensorflow=1.15.5 Python=3.8 Cuda=11.4






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jsp666/CEMBR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月23日(星期四) 中午1:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jsp666/CEMBR] 程序运行环境 (Issue #1)





 
作者大大您好，我对您的工作非常感兴趣，想复现您的工作，可以给出您的程序运行环境吗谢谢！
